if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'Task')
  drop table  Task;
CREATE TABLE [dbo].[Task] (
    [Active]                 BIT             NULL,
    [AssignedTo]             NVARCHAR(max)   NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [BaselineEnd]            DATETIME        NULL,
    [BaselineStart]          DATETIME        NULL,
    [Body]                   NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [Hours]                  FLOAT           NULL,
    [ID]                     INT             NOT NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [Task2CategoryTitle]     INT             NULL,
    [Task2MilestoneDefinedInTitle] INT             NULL,
    [Task2MilestoneResolvedInTitle] INT             NULL,
    [Task2ProjectTitle]      INT             NULL,
    [Task2RequirementsTitle] INT             NULL,
    [Task2SPriorityTitle]    INT             NULL,
    [Task2SResolutionTitle]  INT             NULL,
    [Task2StatusTitle]       INT             NULL,
    [Task2TypeTitle]         INT             NULL,
    [TaskDueDate]            DATETIME        NULL,
    [TaskEnd]                DATETIME        NULL,
    [TaskStart]              DATETIME        NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [OnlySQL]				 BIT			 NOT NULL,	
	CONSTRAINT [PK_Task_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
    CONSTRAINT [FK_Task_Category] FOREIGN KEY ([Task2CategoryTitle]) REFERENCES [dbo].[Category] ([ID]),
    CONSTRAINT [FK_Task_Milestone] FOREIGN KEY ([Task2MilestoneDefinedInTitle]) REFERENCES [dbo].[Milestone] ([ID]),
    CONSTRAINT [FK_Task_Milestone] FOREIGN KEY ([Task2MilestoneResolvedInTitle]) REFERENCES [dbo].[Milestone] ([ID]),
    CONSTRAINT [FK_Task_Projects] FOREIGN KEY ([Task2ProjectTitle]) REFERENCES [dbo].[Projects] ([ID]),
    CONSTRAINT [FK_Task_Requirements] FOREIGN KEY ([Task2RequirementsTitle]) REFERENCES [dbo].[Requirements] ([ID]),
    CONSTRAINT [FK_Task_Priority] FOREIGN KEY ([Task2SPriorityTitle]) REFERENCES [dbo].[Priority] ([ID]),
    CONSTRAINT [FK_Task_Resolution] FOREIGN KEY ([Task2SResolutionTitle]) REFERENCES [dbo].[Resolution] ([ID]),
    CONSTRAINT [FK_Task_SPStatus] FOREIGN KEY ([Task2StatusTitle]) REFERENCES [dbo].[SPStatus] ([ID]),
    CONSTRAINT [FK_Task_Type] FOREIGN KEY ([Task2TypeTitle]) REFERENCES [dbo].[Type] ([ID]),
);
