if exists (select * from INFORMATION_SCHEMA.TABLES where TABLE_NAME = 'Projects')
  drop table  Projects;
CREATE TABLE [dbo].[Projects] (
    [AcceptedHours]          FLOAT           NULL,
    [Active]                 BIT             NULL,
    [AssignedTo]             NVARCHAR(max)   NULL,
    [Author]                 NVARCHAR(max)   NULL,
    [BaselineEnd]            DATETIME        NULL,
    [BaselineStart]          DATETIME        NULL,
    [Body]                   NVARCHAR(max)   NULL,
    [Created]                DATETIME        NULL,
    [Currency]               NVARCHAR(max)   NULL,
    [Editor]                 NVARCHAR(max)   NULL,
    [EstimatedHours]         FLOAT           NULL,
    [ID]                     INT             NOT NULL,
    [MilestoneHours]         FLOAT           NULL,
    [Modified]               DATETIME        NULL,
    [owshiddenversion]       INT             NULL,
    [PONumber]               NVARCHAR(max)   NULL,
    [Project2ContractTitle]  INT             NULL,
    [Project2PartnersTitle]  INT             NULL,
    [Project2StageTitle]     INT             NULL,
    [ProjectBudget]          FLOAT           NULL,
    [ProjectEndDate]         DATETIME        NULL,
    [ProjectHours]           FLOAT           NULL,
    [ProjectNumber]          NVARCHAR(max)   NULL,
    [ProjectStartDate]       DATETIME        NULL,
    [ProjectType]            NVARCHAR(max)   NULL,
    [ProjectWarrantyDate]    DATETIME        NULL,
    [Title]                  NVARCHAR(max)   NOT NULL,
    [OnlySQL]				 BIT			 NOT NULL,	
	CONSTRAINT [PK_Projects_ID] PRIMARY KEY CLUSTERED ([ID] ASC) ,
    CONSTRAINT [FK_Projects_Contracts] FOREIGN KEY ([Project2ContractTitle]) REFERENCES [dbo].[Contracts] ([ID]),
    CONSTRAINT [FK_Projects_Partners] FOREIGN KEY ([Project2PartnersTitle]) REFERENCES [dbo].[Partners] ([ID]),
    CONSTRAINT [FK_Projects_Stage] FOREIGN KEY ([Project2StageTitle]) REFERENCES [dbo].[Stage] ([ID]),
);
