//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:2.0.50727.5456
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace CAS.SharePoint.SPMetalParameters {
    using System.Xml.Serialization;
    
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/SharePoint/2009/spmetal")]
    [System.Xml.Serialization.XmlRootAttribute("Web", Namespace="http://schemas.microsoft.com/SharePoint/2009/spmetal", IsNullable=false)]
    public partial class PRWeb {
        
        private PRList[] listField;
        
        private PRExcludeList[] excludeListField;
        
        private PRFlagElement excludeOtherListsField;
        
        private PRFlagElement includeHiddenListsField;
        
        private PRContentType[] contentTypeField;
        
        private PRExcludeContentType[] excludeContentTypeField;
        
        private PRFlagElement excludeOtherContentTypesField;
        
        private PRFlagElement includeHiddenContentTypesField;
        
        private string classField;
        
        private PRAccessModifier accessModifierField;
        
        public PRWeb() {
            this.accessModifierField = PRAccessModifier.Public;
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute("List")]
        public PRList[] List {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute("ExcludeList")]
        public PRExcludeList[] ExcludeList {
            get {
                return this.excludeListField;
            }
            set {
                this.excludeListField = value;
            }
        }
        
        /// <uwagi/>
        public PRFlagElement ExcludeOtherLists {
            get {
                return this.excludeOtherListsField;
            }
            set {
                this.excludeOtherListsField = value;
            }
        }
        
        /// <uwagi/>
        public PRFlagElement IncludeHiddenLists {
            get {
                return this.includeHiddenListsField;
            }
            set {
                this.includeHiddenListsField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute("ContentType")]
        public PRContentType[] ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute("ExcludeContentType")]
        public PRExcludeContentType[] ExcludeContentType {
            get {
                return this.excludeContentTypeField;
            }
            set {
                this.excludeContentTypeField = value;
            }
        }
        
        /// <uwagi/>
        public PRFlagElement ExcludeOtherContentTypes {
            get {
                return this.excludeOtherContentTypesField;
            }
            set {
                this.excludeOtherContentTypesField = value;
            }
        }
        
        /// <uwagi/>
        public PRFlagElement IncludeHiddenContentTypes {
            get {
                return this.includeHiddenContentTypesField;
            }
            set {
                this.includeHiddenContentTypesField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        [System.ComponentModel.DefaultValueAttribute(PRAccessModifier.Public)]
        public PRAccessModifier AccessModifier {
            get {
                return this.accessModifierField;
            }
            set {
                this.accessModifierField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/SharePoint/2009/spmetal")]
    public partial class PRList {
        
        private PRContentType[] contentTypeField;
        
        private PRExcludeContentType[] excludeContentTypeField;
        
        private string nameField;
        
        private string memberField;
        
        private string typeField;
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute("ContentType")]
        public PRContentType[] ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute("ExcludeContentType")]
        public PRExcludeContentType[] ExcludeContentType {
            get {
                return this.excludeContentTypeField;
            }
            set {
                this.excludeContentTypeField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Member {
            get {
                return this.memberField;
            }
            set {
                this.memberField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/SharePoint/2009/spmetal")]
    public partial class PRContentType {
        
        private PRColumn[] columnField;
        
        private PRExcludeColumn[] excludeColumnField;
        
        private PRFlagElement excludeOtherColumnsField;
        
        private PRFlagElement includeHiddenColumnsField;
        
        private string nameField;
        
        private string classField;
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute("Column")]
        public PRColumn[] Column {
            get {
                return this.columnField;
            }
            set {
                this.columnField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute("ExcludeColumn")]
        public PRExcludeColumn[] ExcludeColumn {
            get {
                return this.excludeColumnField;
            }
            set {
                this.excludeColumnField = value;
            }
        }
        
        /// <uwagi/>
        public PRFlagElement ExcludeOtherColumns {
            get {
                return this.excludeOtherColumnsField;
            }
            set {
                this.excludeOtherColumnsField = value;
            }
        }
        
        /// <uwagi/>
        public PRFlagElement IncludeHiddenColumns {
            get {
                return this.includeHiddenColumnsField;
            }
            set {
                this.includeHiddenColumnsField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Class {
            get {
                return this.classField;
            }
            set {
                this.classField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/SharePoint/2009/spmetal")]
    public partial class PRColumn {
        
        private string nameField;
        
        private string memberField;
        
        private PRType typeField;
        
        private bool typeFieldSpecified;
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Member {
            get {
                return this.memberField;
            }
            set {
                this.memberField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PRType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TypeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/SharePoint/2009/spmetal")]
    public enum PRType {
        
        /// <uwagi/>
        String,
        
        /// <uwagi/>
        Enum,
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/SharePoint/2009/spmetal")]
    public partial class PRExcludeList {
        
        private string nameField;
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/SharePoint/2009/spmetal")]
    public partial class PRExcludeContentType {
        
        private string nameField;
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/SharePoint/2009/spmetal")]
    public partial class PRFlagElement {
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/SharePoint/2009/spmetal")]
    public partial class PRExcludeColumn {
        
        private string nameField;
        
        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/SharePoint/2009/spmetal")]
    public enum PRAccessModifier {
        
        /// <uwagi/>
        Public,
        
        /// <uwagi/>
        Internal,
    }
}
